create table MOCK_DATA (
	 id_feature INT,
	feature_name VARCHAR(50),
	feature_description VARCHAR(50)
);
insert into MOCK_DATA ( id_feature, feature_name, feature_description) values (1, 'Brush-tailed rat kangaroo', 'Unsp Zone II fracture of sacrum, init for opn fx');
insert into MOCK_DATA ( id_feature, feature_name, feature_description) values (2, 'Canada goose', 'Oth water transport accident w military wtrcrft, sequela');
insert into MOCK_DATA ( id_feature, feature_name, feature_description) values (3, 'Old world fruit bat (unidentified)', 'Poisoning by tetracyclic antidepressants, self-harm');
insert into MOCK_DATA ( id_feature, feature_name, feature_description) values (4, 'Praying mantis (unidentified)', 'Injury of digital nerve of left middle finger, sequela');
insert into MOCK_DATA ( id_feature, feature_name, feature_description) values (5, 'Common duiker', 'Oth diabetes with diabetic macular edema, resolved fol trtmt');
insert into MOCK_DATA ( id_feature, feature_name, feature_description) values (6, 'Squirrel glider', 'Displ avuls fx tuberosity of unsp calcaneus, 7thG');
insert into MOCK_DATA ( id_feature, feature_name, feature_description) values (7, 'Baboon, olive', 'Corrosion of unspecified degree of right shoulder');
insert into MOCK_DATA ( id_feature, feature_name, feature_description) values (8, 'Partridge, coqui', 'Disp fx of med condyle of unsp tibia, 7thN');
insert into MOCK_DATA ( id_feature, feature_name, feature_description) values (9, 'Crab, sally lightfoot', 'Reiter''s disease, left shoulder');
insert into MOCK_DATA ( id_feature, feature_name, feature_description) values (10, 'African red-eyed bulbul', 'Sltr-haris Type I physl fx low end humer, r arm, 7thG');
insert into MOCK_DATA ( id_feature, feature_name, feature_description) values (11, 'Elegant crested tinamou', 'Presence of unspecified artificial elbow joint');
insert into MOCK_DATA ( id_feature, feature_name, feature_description) values (12, 'White-winged dove', 'Age-rel osteopor w crnt path fx, unsp shldr, 7thD');
insert into MOCK_DATA ( id_feature, feature_name, feature_description) values (13, 'Southern sea lion', 'Unsp injury of unsp musc/tend at lower leg level, unsp leg');
insert into MOCK_DATA ( id_feature, feature_name, feature_description) values (14, 'Mongoose, yellow', 'Nondisp fx of med malleolus of unsp tibia, 7thM');
insert into MOCK_DATA ( id_feature, feature_name, feature_description) values (15, 'Pheasant, common', 'External constriction of right shoulder, initial encounter');
insert into MOCK_DATA ( id_feature, feature_name, feature_description) values (16, 'Slender loris', 'Contact with hot toaster, sequela');
insert into MOCK_DATA ( id_feature, feature_name, feature_description) values (17, 'Eagle, bateleur', 'Varicose veins of unspecified lower extremity with ulcer');
insert into MOCK_DATA ( id_feature, feature_name, feature_description) values (18, 'Scarlet macaw', 'Activity, other involving cooking and grilling');
insert into MOCK_DATA ( id_feature, feature_name, feature_description) values (19, 'Screamer, southern', 'Athscl autologous artery CABG w unsp angina pectoris');
insert into MOCK_DATA ( id_feature, feature_name, feature_description) values (20, 'Potoroo', 'Pathological fracture in other disease, left ulna, sequela');
insert into MOCK_DATA ( id_feature, feature_name, feature_description) values (21, 'Phalarope, red', 'Toxic effect of venom of African and Asian snake, acc');
insert into MOCK_DATA ( id_feature, feature_name, feature_description) values (22, 'Malagasy ground boa', 'Anoxic brain damage, not elsewhere classified');
insert into MOCK_DATA ( id_feature, feature_name, feature_description) values (23, 'Wild water buffalo', 'Complete traumatic amp at elbow level, left arm, sequela');
insert into MOCK_DATA ( id_feature, feature_name, feature_description) values (24, 'Tammar wallaby', 'Toxic effect of arsenic and its compounds, undet, init');
insert into MOCK_DATA ( id_feature, feature_name, feature_description) values (25, 'African black crake', 'Nondisp fx of distal phalanx of right ring finger, init');
insert into MOCK_DATA ( id_feature, feature_name, feature_description) values (26, 'Cereopsis goose', 'Unspecified open wound of left breast');
insert into MOCK_DATA ( id_feature, feature_name, feature_description) values (27, 'Chestnut weaver', 'Contusion of great toe without damage to nail');
insert into MOCK_DATA ( id_feature, feature_name, feature_description) values (28, 'Purple moorhen', 'Occ of rail trn/veh injured by fall in rail trn/veh, init');
insert into MOCK_DATA ( id_feature, feature_name, feature_description) values (29, 'Alpaca', 'War op w dest arcrft due to acc deton onboard munit, milt');
insert into MOCK_DATA ( id_feature, feature_name, feature_description) values (30, 'Common dolphin', 'Disp fx of medial condyle of left humerus, init for opn fx');
insert into MOCK_DATA ( id_feature, feature_name, feature_description) values (31, 'Ring dove', 'Unspecified subluxation of unspecified knee, sequela');
insert into MOCK_DATA ( id_feature, feature_name, feature_description) values (32, 'Western spotted skunk', 'Disp fx of dist pole of navic bone of unsp wrs, 7thK');
insert into MOCK_DATA ( id_feature, feature_name, feature_description) values (33, 'Snake, eastern indigo', 'Oth diab w prolif diab rtnop with trctn dtch macula, l eye');
insert into MOCK_DATA ( id_feature, feature_name, feature_description) values (34, 'Guerza', 'Traum rupture of left ulnocarpal (palmar) ligament, sequela');
insert into MOCK_DATA ( id_feature, feature_name, feature_description) values (35, 'Red meerkat', 'Laceration with foreign body, unspecified foot, subs encntr');
insert into MOCK_DATA ( id_feature, feature_name, feature_description) values (36, 'Cape wild cat', 'Nondisp unsp fracture of unsp lesser toe(s), init for opn fx');
insert into MOCK_DATA ( id_feature, feature_name, feature_description) values (37, 'Deer, spotted', 'Opioid use, unsp with opioid-induced psychotic disorder');
insert into MOCK_DATA ( id_feature, feature_name, feature_description) values (38, 'Gray langur', 'Contact with and (suspected) exposure to meningococcus');
insert into MOCK_DATA ( id_feature, feature_name, feature_description) values (39, 'Brocket, red', 'Other arthritis');
insert into MOCK_DATA ( id_feature, feature_name, feature_description) values (40, 'Red-legged pademelon', 'Nodular corneal degeneration, unspecified eye');
insert into MOCK_DATA ( id_feature, feature_name, feature_description) values (41, 'Squirrel, golden-mantled ground', 'Poisoning by caffeine, assault, subsequent encounter');
insert into MOCK_DATA ( id_feature, feature_name, feature_description) values (42, 'Violet-crested turaco', 'Disp fx of shaft of unsp clavicle, subs for fx w nonunion');
insert into MOCK_DATA ( id_feature, feature_name, feature_description) values (43, 'Australian masked owl', 'Finding of alcohol in blood');
insert into MOCK_DATA ( id_feature, feature_name, feature_description) values (44, 'Lapwing (unidentified)', 'Exposure to chng in air pressure in aircraft during ascent');
insert into MOCK_DATA ( id_feature, feature_name, feature_description) values (45, 'Square-lipped rhinoceros', 'Assault by unspecified larger firearm discharge, init encntr');
insert into MOCK_DATA ( id_feature, feature_name, feature_description) values (46, 'Pale white-eye', 'Passenger on bus injured in collision w unsp mv nontraf');
insert into MOCK_DATA ( id_feature, feature_name, feature_description) values (47, 'Racer, american', 'Scombroid fish poisoning, assault, subsequent encounter');
insert into MOCK_DATA ( id_feature, feature_name, feature_description) values (48, 'Bushbuck', 'Nondisplaced fracture of neck of right talus');
insert into MOCK_DATA ( id_feature, feature_name, feature_description) values (49, 'Yellow-billed hornbill', 'Sprain of interphalangeal joint of other finger, sequela');
insert into MOCK_DATA ( id_feature, feature_name, feature_description) values (50, 'Western grey kangaroo', 'Rheumatic tricuspid valve disease, unspecified');
insert into MOCK_DATA ( id_feature, feature_name, feature_description) values (51, 'Wattled crane', 'Avulsion of left eye, subsequent encounter');
insert into MOCK_DATA ( id_feature, feature_name, feature_description) values (52, 'North American red fox', 'Toxic effect of venom of reptiles, accidental');
insert into MOCK_DATA ( id_feature, feature_name, feature_description) values (53, 'Short-nosed bandicoot', 'Burn of first deg mult fingers (nail), including thumb');
insert into MOCK_DATA ( id_feature, feature_name, feature_description) values (54, 'Asian false vampire bat', 'Nondisp fx of medial malleolus of left tibia, init');
insert into MOCK_DATA ( id_feature, feature_name, feature_description) values (55, 'Parrot, hawk-headed', 'Age-rel osteopor w current path fracture, r hand, sequela');
insert into MOCK_DATA ( id_feature, feature_name, feature_description) values (56, 'Macaque, rhesus', 'Nondisp transverse fx l patella, 7thE');
insert into MOCK_DATA ( id_feature, feature_name, feature_description) values (57, 'Tropical buckeye butterfly', 'Nondisp fx of second metatarsal bone, unspecified foot');
insert into MOCK_DATA ( id_feature, feature_name, feature_description) values (58, 'Agile wallaby', 'Prsn brd/alit a pedal cycle injured pick-up truck, pk-up/van');
insert into MOCK_DATA ( id_feature, feature_name, feature_description) values (59, 'Buffalo, african', 'Measles complicated by encephalitis');
insert into MOCK_DATA ( id_feature, feature_name, feature_description) values (60, 'Rainbow lory', 'Toxic effect of other pesticides, undetermined, init encntr');
insert into MOCK_DATA ( id_feature, feature_name, feature_description) values (61, 'Snowy owl', 'Injury of axillary nerve, unspecified arm');
insert into MOCK_DATA ( id_feature, feature_name, feature_description) values (62, 'Stork, jabiru', 'Car passenger injured in clsn w pedl cyc nontraf, sequela');
insert into MOCK_DATA ( id_feature, feature_name, feature_description) values (63, 'Ring dove', 'Non-pressure chronic ulcer of calf');
insert into MOCK_DATA ( id_feature, feature_name, feature_description) values (64, 'Waved albatross', 'Conjunctival granuloma, left eye');
insert into MOCK_DATA ( id_feature, feature_name, feature_description) values (65, 'Squirrel, palm', 'External constriction of oral cavity');
insert into MOCK_DATA ( id_feature, feature_name, feature_description) values (66, 'Pacific gull', 'Central retinal vein occlusion, unsp, w rtnl neovas');
insert into MOCK_DATA ( id_feature, feature_name, feature_description) values (67, 'Lynx, african', 'Toxic effect of contact w sea anemone, accidental');
insert into MOCK_DATA ( id_feature, feature_name, feature_description) values (68, 'Cat, long-tailed spotted', 'Unspecified injury of ureter');
insert into MOCK_DATA ( id_feature, feature_name, feature_description) values (69, 'Yellow-throated sandgrouse', 'Astrovirus enteritis');
insert into MOCK_DATA ( id_feature, feature_name, feature_description) values (70, 'Weaver, red-billed buffalo', 'Burn 2nd deg of unsp site right lower limb, ex ank/ft, subs');
insert into MOCK_DATA ( id_feature, feature_name, feature_description) values (71, 'Worm snake (unidentified)', 'Phlyctenular keratoconjunctivitis, bilateral');
insert into MOCK_DATA ( id_feature, feature_name, feature_description) values (72, 'Cape cobra', 'Pasngr in 3-whl mv injured in clsn w unsp mv in traf, init');
insert into MOCK_DATA ( id_feature, feature_name, feature_description) values (73, 'Lily trotter', 'Spacecraft collision injuring occupant, subsequent encounter');
insert into MOCK_DATA ( id_feature, feature_name, feature_description) values (74, 'Swan, black', 'Nondisp fx of med condyle of unsp humer, 7thP');
insert into MOCK_DATA ( id_feature, feature_name, feature_description) values (75, 'Shrike, crimson-breasted', 'Contracture of muscle, shoulder');
insert into MOCK_DATA ( id_feature, feature_name, feature_description) values (76, 'Gecko, tokay', 'Oth foreign object in trachea causing asphyxiation, init');
insert into MOCK_DATA ( id_feature, feature_name, feature_description) values (77, 'Arctic ground squirrel', 'Disp fx of posterior column of right acetabulum, init');
insert into MOCK_DATA ( id_feature, feature_name, feature_description) values (78, 'Galapagos hawk', 'Passenger injured in collision w unsp mv nontraf, init');
insert into MOCK_DATA ( id_feature, feature_name, feature_description) values (79, 'Dove, ring', 'Pathological fracture, unspecified toe(s)');
insert into MOCK_DATA ( id_feature, feature_name, feature_description) values (80, 'Richardson''s ground squirrel', 'Displ seg fx shaft of r tibia, init for opn fx type 3A/B/C');
insert into MOCK_DATA ( id_feature, feature_name, feature_description) values (81, 'Arboral spiny rat', 'Disp fx of dist phalanx of l lit fngr, 7thG');
insert into MOCK_DATA ( id_feature, feature_name, feature_description) values (82, 'Cobra (unidentified)', 'Turner''s syndrome');
insert into MOCK_DATA ( id_feature, feature_name, feature_description) values (83, 'Dove, mourning collared', 'Nondisp commnt fx shaft of l tibia, 7thG');
insert into MOCK_DATA ( id_feature, feature_name, feature_description) values (84, 'Mourning collared dove', 'Open bite of l bk wl of thorax w penet thor cavity, sequela');
insert into MOCK_DATA ( id_feature, feature_name, feature_description) values (85, 'Carmine bee-eater', 'Post-traumatic stress disorder, acute');
insert into MOCK_DATA ( id_feature, feature_name, feature_description) values (86, 'Monkey, rhesus', 'Nondisp fx of prox phalanx of thmb, subs for fx w routn heal');
insert into MOCK_DATA ( id_feature, feature_name, feature_description) values (87, 'Chestnut weaver', 'Intcran inj w LOC of unsp duration, sequela');
insert into MOCK_DATA ( id_feature, feature_name, feature_description) values (88, 'Goose, greylag', 'Arthropathy following intestinal bypass, right wrist');
insert into MOCK_DATA ( id_feature, feature_name, feature_description) values (89, 'Grey lourie', 'Strain of unsp musc/fasc/tend at thi lev, left thigh, init');
insert into MOCK_DATA ( id_feature, feature_name, feature_description) values (90, 'Brocket, brown', 'Contact with hotplate, sequela');
insert into MOCK_DATA ( id_feature, feature_name, feature_description) values (91, 'Bee-eater, nubian', 'Unspecified open wound of unspecified elbow, sequela');
insert into MOCK_DATA ( id_feature, feature_name, feature_description) values (92, 'Shark, blue', 'Milt op involving unsp dest arcrft, military personnel, init');
insert into MOCK_DATA ( id_feature, feature_name, feature_description) values (93, 'Vulture, king', 'Atheroembolism of right upper extremity');
insert into MOCK_DATA ( id_feature, feature_name, feature_description) values (94, 'Collared lizard', 'Displ commnt fx shaft of unsp fibula, 7thB');
insert into MOCK_DATA ( id_feature, feature_name, feature_description) values (95, 'Frilled dragon', 'Hallux rigidus, right foot');
insert into MOCK_DATA ( id_feature, feature_name, feature_description) values (96, 'Macaque, rhesus', 'Disp fx of base of 5th MC bone. l hand, 7thD');
insert into MOCK_DATA ( id_feature, feature_name, feature_description) values (97, 'Monkey, bleeding heart', 'Poisn by emollients, demulcents and protect, undet, sequela');
insert into MOCK_DATA ( id_feature, feature_name, feature_description) values (98, 'Baboon, gelada', 'Type 1 diabetes mellitus with diabetic neuropathy, unsp');
insert into MOCK_DATA ( id_feature, feature_name, feature_description) values (99, 'Blue racer', 'Sprain of lateral collateral ligament of right knee, init');
insert into MOCK_DATA ( id_feature, feature_name, feature_description) values (100, 'Carpet snake', 'Nondisp fx of mid 3rd of navic bone of unsp wrs, 7thB');
